services:
  # MySQL 서비스 정의
  db:
    image: mysql:8.0  # MySQL 이미지 및 버전
    container_name: mysql-container  # 컨테이너 이름
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}  # db 사용자 비밀번호
      MYSQL_DATABASE: ${DB}  # 생성할 기본 데이터베이스 이름
      MYSQL_USER: ${DB_USER}  # 일반 사용자 이름
      MYSQL_PASSWORD: ${DB_PASSWORD}  # 일반 사용자 비밀번호
    restart: on-failure
    ports:
      - "${DB_PORT}:${DB_PORT}"  # DB 서버 포트 연결
    volumes:
      - mysql_data:/var/lib/mysql  # MySQL 데이터를 저장할 볼륨 정의
    networks:
      - solo_play_net


  # Spring Boot 서비스 정의
  app:
    image: ${IMAGE_NAME}  # 빌드된 Spring Boot Docker 이미지
    container_name: solo-play-server-container  # 컨테이너 이름
    depends_on:
      - db  # db 서비스가 준비된 후에 실행되도록 설정
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB}?autoReconnect=true&useUnicode=true&serverTimezone=Asia/Seoul  # MySQL 연결 URL
      SPRING_DATASOURCE_USERNAME: ${DB_USER}  # 데이터베이스 사용자 이름
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}  # 데이터베이스 사용자 비밀번호
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"  # 포트 연결
    restart: on-failure
    networks:
      - solo_play_net

networks:
  solo_play_net: {}

volumes:
  mysql_data: