spring:
  application:
    name: solo_play_web_server
  config:
    import: optional:file:.env[.properties]

  sql:
    init:
      mode: always

  r2dbc:
    url: r2dbc:pool:mysql://${DB_URL}:${DB_PORT}/${DB}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  data:
    r2dbc:
      repositories:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
