spring:
  application:
    name: solo_play_web_server
  config:
    import: optional:file:.env[.properties]

  sql:
    init:
      mode: always

  r2dbc:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  data:
    r2dbc:
      repositories:
        enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
