spring:
  application:
    name: solo_play_web_server
  config:
    import: optional:file:.env[.properties]

  sql:
    init:
      mode: always

  r2dbc:
    url: r2dbc:pool:mysql://${DB_URL}:${DB_PORT}/${DB}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  data:
    r2dbc:
      repositories:
        enabled: true

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: "jdbc:mysql://${DB_URL}:${DB_PORT}/${DB}?autoReconnect=true&useUnicode=true&serverTimezone=Asia/Seoul"
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    properties:
#      hibernate:
#        storage_engine: innodb
#        format_sql: true
#        use_sql_comments: true
#    hibernate:
#      ddl-auto: create
#    open-in-view: false
#    show_sql: true
#jwt:
#  secret:{JWT_SECRET}

